server:
  port: 1010
spring:
  datasource:
    url: jdbc:mysql://localhost:2234/ETSK?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false
  security:
   secret: Qi5ncmIndCxiLHI7dCx0cjZ0NGI4boxenJ0YjR0cmViZWE4NDg2NHRiODQ2cjQ2dHI0Yg==
   token:
    expirationTime: 120




